// This file is auto-generated by @hey-api/openapi-ts

import type {
  Options as ClientOptions,
  TDataShape,
  Client,
} from '@hey-api/client-axios';
import type {
  PostAuthRegisterData,
  PostAuthRegisterResponse,
  PostAuthRegisterError,
  PostAuthLoginData,
  PostAuthLoginResponse,
  PostAuthLoginError,
  GetExercisesData,
  GetExercisesResponse,
  GetExercisesError,
  PostExercisesData,
  PostExercisesResponse,
  PostExercisesError,
  PutExercisesData,
  PutExercisesResponse,
  PutExercisesError,
  GetExercisesBuiltInData,
  GetExercisesBuiltInResponse,
  GetExercisesBuiltInError,
  DeleteExercisesByIdData,
  DeleteExercisesByIdResponse,
  DeleteExercisesByIdError,
  GetExercisesByIdData,
  GetExercisesByIdResponse,
  GetExercisesByIdError,
  PatchExercisesByIdData,
  PatchExercisesByIdResponse,
  PatchExercisesByIdError,
  GetWorkoutsData,
  GetWorkoutsResponse,
  GetWorkoutsError,
  PostWorkoutsData,
  PostWorkoutsResponse,
  PostWorkoutsError,
  PutWorkoutsData,
  PutWorkoutsResponse,
  PutWorkoutsError,
  DeleteWorkoutsByIdData,
  DeleteWorkoutsByIdResponse,
  DeleteWorkoutsByIdError,
  GetWorkoutsByIdData,
  GetWorkoutsByIdResponse,
  GetWorkoutsByIdError,
  PatchWorkoutsByIdData,
  PatchWorkoutsByIdResponse,
  PatchWorkoutsByIdError,
  GetWorkoutPlansData,
  GetWorkoutPlansResponse,
  GetWorkoutPlansError,
  PostWorkoutPlansData,
  PostWorkoutPlansResponse,
  PostWorkoutPlansError,
  DeleteWorkoutPlansByIdData,
  DeleteWorkoutPlansByIdResponse,
  DeleteWorkoutPlansByIdError,
  GetWorkoutPlansByIdData,
  GetWorkoutPlansByIdResponse,
  GetWorkoutPlansByIdError,
  PatchWorkoutPlansByIdData,
  PatchWorkoutPlansByIdResponse,
  PatchWorkoutPlansByIdError,
  GetWorkoutTypesData,
  GetWorkoutTypesResponse,
  GetWorkoutTypesError,
  PostWorkoutTypesData,
  PostWorkoutTypesResponse,
  PostWorkoutTypesError,
  DeleteWorkoutTypesByIdData,
  DeleteWorkoutTypesByIdResponse,
  DeleteWorkoutTypesByIdError,
  GetWorkoutTypesByIdData,
  GetWorkoutTypesByIdResponse,
  GetWorkoutTypesByIdError,
  PatchWorkoutTypesByIdData,
  PatchWorkoutTypesByIdResponse,
  PatchWorkoutTypesByIdError,
  PostWeightData,
  PostWeightResponse,
  PostWeightError,
  GetWeightByIdData,
  GetWeightByIdResponse,
  GetWeightByIdError,
  PatchWeightByIdData,
  PatchWeightByIdResponse,
  PatchWeightByIdError,
  GetArgusCheckinData,
  GetArgusCheckinResponse,
  GetArgusCheckinError,
  GetArgusCheckinTypesData,
  GetArgusCheckinTypesResponse,
  GetArgusCheckinTypesError,
  GetEntriesData,
  GetEntriesResponse,
  GetEntriesError,
  GetEntriesOwnData,
  GetEntriesOwnResponse,
  GetEntriesOwnError,
  GetCrmUsersData,
  GetCrmUsersResponse,
  GetCrmUsersError,
  GetCrmManagersData,
  GetCrmManagersResponse,
  GetCrmManagersError,
  PostCrmAuthLoginData,
  PostCrmAuthLoginResponse,
  PostCrmAuthLoginError,
  GetCrmTranslationsByIdData,
  GetCrmTranslationsByIdResponse,
  GetCrmTranslationsByIdError,
  PatchCrmTranslationsByIdData,
  PatchCrmTranslationsByIdResponse,
  PatchCrmTranslationsByIdError,
  GetCrmTranslationsData,
  GetCrmTranslationsResponse,
  GetCrmTranslationsError,
  GetCrmExercisesByIdData,
  GetCrmExercisesByIdResponse,
  GetCrmExercisesByIdError,
  PatchCrmExercisesByIdData,
  PatchCrmExercisesByIdResponse,
  PatchCrmExercisesByIdError,
  GetCrmExercisesData,
  GetCrmExercisesResponse,
  GetCrmExercisesError,
  GetCrmImagesData,
  GetCrmImagesResponse,
  GetCrmImagesError,
  DeleteCrmImagesByIdData,
  DeleteCrmImagesByIdResponse,
  DeleteCrmImagesByIdError,
} from './types.gen';
import {client as _heyApiClient} from './client.gen';
import {
  getExercisesResponseTransformer,
  postExercisesResponseTransformer,
  putExercisesResponseTransformer,
  getExercisesBuiltInResponseTransformer,
  getExercisesByIdResponseTransformer,
  getWorkoutsResponseTransformer,
  postWorkoutsResponseTransformer,
  putWorkoutsResponseTransformer,
  getWorkoutsByIdResponseTransformer,
  patchWorkoutsByIdResponseTransformer,
  getWorkoutPlansResponseTransformer,
  postWorkoutPlansResponseTransformer,
  getWorkoutPlansByIdResponseTransformer,
  patchWorkoutPlansByIdResponseTransformer,
  getWorkoutTypesResponseTransformer,
  postWorkoutTypesResponseTransformer,
  getWorkoutTypesByIdResponseTransformer,
  patchWorkoutTypesByIdResponseTransformer,
  postWeightResponseTransformer,
  getWeightByIdResponseTransformer,
  patchWeightByIdResponseTransformer,
  getArgusCheckinResponseTransformer,
  getEntriesResponseTransformer,
  getEntriesOwnResponseTransformer,
  getCrmManagersResponseTransformer,
  getCrmTranslationsByIdResponseTransformer,
  patchCrmTranslationsByIdResponseTransformer,
  getCrmTranslationsResponseTransformer,
  getCrmExercisesByIdResponseTransformer,
  getCrmExercisesResponseTransformer,
  getCrmImagesResponseTransformer,
} from './transformers.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Registers a user
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(
  options?: Options<PostAuthRegisterData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostAuthRegisterResponse,
    PostAuthRegisterError,
    ThrowOnError
  >({
    url: '/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Logins a user
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(
  options?: Options<PostAuthLoginData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostAuthLoginResponse,
    PostAuthLoginError,
    ThrowOnError
  >({
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns data on exercises available to the user
 */
export const getExercises = <ThrowOnError extends boolean = false>(
  options?: Options<GetExercisesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetExercisesResponse,
    GetExercisesError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getExercisesResponseTransformer,
    url: '/exercises',
    ...options,
  });
};

/**
 * Adds new exercise to the user personal library
 */
export const postExercises = <ThrowOnError extends boolean = false>(
  options?: Options<PostExercisesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostExercisesResponse,
    PostExercisesError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: postExercisesResponseTransformer,
    url: '/exercises',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Updates or inserts exercise in users personal library
 */
export const putExercises = <ThrowOnError extends boolean = false>(
  options?: Options<PutExercisesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).put<
    PutExercisesResponse,
    PutExercisesError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: putExercisesResponseTransformer,
    url: '/exercises',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns data on exercises available to the user
 */
export const getExercisesBuiltIn = <ThrowOnError extends boolean = false>(
  options?: Options<GetExercisesBuiltInData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetExercisesBuiltInResponse,
    GetExercisesBuiltInError,
    ThrowOnError
  >({
    responseTransformer: getExercisesBuiltInResponseTransformer,
    url: '/exercises/built-in',
    ...options,
  });
};

/**
 * Deletes exercise from users personal library
 */
export const deleteExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteExercisesByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteExercisesByIdResponse,
    DeleteExercisesByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    url: '/exercises/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns data on an library exercise available
 */
export const getExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<GetExercisesByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetExercisesByIdResponse,
    GetExercisesByIdError,
    ThrowOnError
  >({
    responseTransformer: getExercisesByIdResponseTransformer,
    url: '/exercises/{id}',
    ...options,
  });
};

/**
 * Updates exercise in users personal library
 */
export const patchExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<PatchExercisesByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchExercisesByIdResponse,
    PatchExercisesByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    url: '/exercises/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns list of user workouts
 */
export const getWorkouts = <ThrowOnError extends boolean = false>(
  options?: Options<GetWorkoutsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWorkoutsResponse,
    GetWorkoutsError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getWorkoutsResponseTransformer,
    url: '/workouts',
    ...options,
  });
};

/**
 * Adds new workout for the user
 */
export const postWorkouts = <ThrowOnError extends boolean = false>(
  options?: Options<PostWorkoutsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWorkoutsResponse,
    PostWorkoutsError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: postWorkoutsResponseTransformer,
    url: '/workouts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Updates or inserts workout for user
 */
export const putWorkouts = <ThrowOnError extends boolean = false>(
  options?: Options<PutWorkoutsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).put<
    PutWorkoutsResponse,
    PutWorkoutsError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: putWorkoutsResponseTransformer,
    url: '/workouts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Deletes workout from user
 */
export const deleteWorkoutsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWorkoutsByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteWorkoutsByIdResponse,
    DeleteWorkoutsByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    url: '/workouts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns data on user workout
 */
export const getWorkoutsById = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkoutsByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetWorkoutsByIdResponse,
    GetWorkoutsByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getWorkoutsByIdResponseTransformer,
    url: '/workouts/{id}',
    ...options,
  });
};

/**
 * Updates workout of current user
 */
export const patchWorkoutsById = <ThrowOnError extends boolean = false>(
  options: Options<PatchWorkoutsByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchWorkoutsByIdResponse,
    PatchWorkoutsByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: patchWorkoutsByIdResponseTransformer,
    url: '/workouts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns list of user workout plans
 */
export const getWorkoutPlans = <ThrowOnError extends boolean = false>(
  options?: Options<GetWorkoutPlansData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWorkoutPlansResponse,
    GetWorkoutPlansError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getWorkoutPlansResponseTransformer,
    url: '/workout-plans',
    ...options,
  });
};

/**
 * Adds new workout plan for the user
 */
export const postWorkoutPlans = <ThrowOnError extends boolean = false>(
  options?: Options<PostWorkoutPlansData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWorkoutPlansResponse,
    PostWorkoutPlansError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: postWorkoutPlansResponseTransformer,
    url: '/workout-plans',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Deletes workout plan
 */
export const deleteWorkoutPlansById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWorkoutPlansByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteWorkoutPlansByIdResponse,
    DeleteWorkoutPlansByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    url: '/workout-plans/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns data on user workout plan
 */
export const getWorkoutPlansById = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkoutPlansByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetWorkoutPlansByIdResponse,
    GetWorkoutPlansByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getWorkoutPlansByIdResponseTransformer,
    url: '/workout-plans/{id}',
    ...options,
  });
};

/**
 * Updated workout plan for the user
 */
export const patchWorkoutPlansById = <ThrowOnError extends boolean = false>(
  options: Options<PatchWorkoutPlansByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchWorkoutPlansByIdResponse,
    PatchWorkoutPlansByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: patchWorkoutPlansByIdResponseTransformer,
    url: '/workout-plans/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns list of user workout plans
 */
export const getWorkoutTypes = <ThrowOnError extends boolean = false>(
  options?: Options<GetWorkoutTypesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWorkoutTypesResponse,
    GetWorkoutTypesError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getWorkoutTypesResponseTransformer,
    url: '/workout-types',
    ...options,
  });
};

/**
 * Adds new workout type for the user
 */
export const postWorkoutTypes = <ThrowOnError extends boolean = false>(
  options?: Options<PostWorkoutTypesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWorkoutTypesResponse,
    PostWorkoutTypesError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: postWorkoutTypesResponseTransformer,
    url: '/workout-types',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Deletes workout type
 */
export const deleteWorkoutTypesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWorkoutTypesByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteWorkoutTypesByIdResponse,
    DeleteWorkoutTypesByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    url: '/workout-types/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns data on user workout type
 */
export const getWorkoutTypesById = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkoutTypesByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetWorkoutTypesByIdResponse,
    GetWorkoutTypesByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getWorkoutTypesByIdResponseTransformer,
    url: '/workout-types/{id}',
    ...options,
  });
};

/**
 * Updated workout type for the user
 */
export const patchWorkoutTypesById = <ThrowOnError extends boolean = false>(
  options: Options<PatchWorkoutTypesByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchWorkoutTypesByIdResponse,
    PatchWorkoutTypesByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: patchWorkoutTypesByIdResponseTransformer,
    url: '/workout-types/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Adds new weight entry for the user
 */
export const postWeight = <ThrowOnError extends boolean = false>(
  options?: Options<PostWeightData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWeightResponse,
    PostWeightError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: postWeightResponseTransformer,
    url: '/weight',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Gets own weight entry for the user
 */
export const getWeightById = <ThrowOnError extends boolean = false>(
  options: Options<GetWeightByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetWeightByIdResponse,
    GetWeightByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getWeightByIdResponseTransformer,
    url: '/weight/{id}',
    ...options,
  });
};

/**
 * Updates own weight entry for the user
 */
export const patchWeightById = <ThrowOnError extends boolean = false>(
  options: Options<PatchWeightByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchWeightByIdResponse,
    PatchWeightByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: patchWeightByIdResponseTransformer,
    url: '/weight/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns data on all checkins from Argus
 */
export const getArgusCheckin = <ThrowOnError extends boolean = false>(
  options?: Options<GetArgusCheckinData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetArgusCheckinResponse,
    GetArgusCheckinError,
    ThrowOnError
  >({
    responseTransformer: getArgusCheckinResponseTransformer,
    url: '/argus/checkin',
    ...options,
  });
};

/**
 * Returns possible checkin types for Argus
 */
export const getArgusCheckinTypes = <ThrowOnError extends boolean = false>(
  options?: Options<GetArgusCheckinTypesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetArgusCheckinTypesResponse,
    GetArgusCheckinTypesError,
    ThrowOnError
  >({
    url: '/argus/checkin/types',
    ...options,
  });
};

/**
 * Returns the list of public entries
 */
export const getEntries = <ThrowOnError extends boolean = false>(
  options?: Options<GetEntriesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetEntriesResponse,
    GetEntriesError,
    ThrowOnError
  >({
    responseTransformer: getEntriesResponseTransformer,
    url: '/entries',
    ...options,
  });
};

/**
 * Returns the list of public entries
 */
export const getEntriesOwn = <ThrowOnError extends boolean = false>(
  options?: Options<GetEntriesOwnData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetEntriesOwnResponse,
    GetEntriesOwnError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getEntriesOwnResponseTransformer,
    url: '/entries/own',
    ...options,
  });
};

/**
 * Returns list of users
 */
export const getCrmUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetCrmUsersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCrmUsersResponse,
    GetCrmUsersError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    url: '/crm/users',
    ...options,
  });
};

/**
 * Returns list of managers
 */
export const getCrmManagers = <ThrowOnError extends boolean = false>(
  options?: Options<GetCrmManagersData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCrmManagersResponse,
    GetCrmManagersError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getCrmManagersResponseTransformer,
    url: '/crm/managers',
    ...options,
  });
};

/**
 * Logins a manager into CRM
 */
export const postCrmAuthLogin = <ThrowOnError extends boolean = false>(
  options?: Options<PostCrmAuthLoginData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    PostCrmAuthLoginResponse,
    PostCrmAuthLoginError,
    ThrowOnError
  >({
    url: '/crm/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns translation
 */
export const getCrmTranslationsById = <ThrowOnError extends boolean = false>(
  options: Options<GetCrmTranslationsByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetCrmTranslationsByIdResponse,
    GetCrmTranslationsByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getCrmTranslationsByIdResponseTransformer,
    url: '/crm/translations/{id}',
    ...options,
  });
};

/**
 * Updates translation
 */
export const patchCrmTranslationsById = <ThrowOnError extends boolean = false>(
  options: Options<PatchCrmTranslationsByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchCrmTranslationsByIdResponse,
    PatchCrmTranslationsByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: patchCrmTranslationsByIdResponseTransformer,
    url: '/crm/translations/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns list of translations
 */
export const getCrmTranslations = <ThrowOnError extends boolean = false>(
  options?: Options<GetCrmTranslationsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCrmTranslationsResponse,
    GetCrmTranslationsError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getCrmTranslationsResponseTransformer,
    url: '/crm/translations',
    ...options,
  });
};

/**
 * Returns data on an exercise
 */
export const getCrmExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<GetCrmExercisesByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    GetCrmExercisesByIdResponse,
    GetCrmExercisesByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getCrmExercisesByIdResponseTransformer,
    url: '/crm/exercises/{id}',
    ...options,
  });
};

/**
 * Updates exercise
 */
export const patchCrmExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<PatchCrmExercisesByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchCrmExercisesByIdResponse,
    PatchCrmExercisesByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    url: '/crm/exercises/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Returns data on exercises
 */
export const getCrmExercises = <ThrowOnError extends boolean = false>(
  options?: Options<GetCrmExercisesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCrmExercisesResponse,
    GetCrmExercisesError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getCrmExercisesResponseTransformer,
    url: '/crm/exercises',
    ...options,
  });
};

/**
 * Returns data on images
 */
export const getCrmImages = <ThrowOnError extends boolean = false>(
  options?: Options<GetCrmImagesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCrmImagesResponse,
    GetCrmImagesError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    responseTransformer: getCrmImagesResponseTransformer,
    url: '/crm/images',
    ...options,
  });
};

/**
 * Deletes image
 */
export const deleteCrmImagesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCrmImagesByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteCrmImagesByIdResponse,
    DeleteCrmImagesByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: 'authorization',
        type: 'apiKey',
      },
    ],
    url: '/crm/images/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};
